data_ingestion:
  url: https://raw.githubusercontent.com/vikashishere/Datasets/main/spam.csv
  output_dir: data/raw
  test_size: 0.3
  random_state: 42

data_preprocessing:
  train_input_path: data/raw/train.csv
  test_input_path: data/raw/test.csv
  train_output_path: data/processed/train.csv
  test_output_path: data/processed/test.csv
  label_column: label
  text_column: message

feature_engineering:
  train_path: data/processed/train.csv
  test_path: data/processed/test.csv
  output_dir: data/features
  text_column: message
  label_column: label
  max_features: 30
  ngram_range: [1, 2]

model_building:
  features_path: data/features/X_train.npz
  labels_path: data/features/y_train.csv
  model_path: model/model.pkl
  label_column: label
  max_iter: 1000
  random_state: 42
  dvclive_dir: dvclive/train

model_evaluation:
  model_path: model/model.pkl
  features_path: data/features/X_test.npz
  labels_path: data/features/y_test.csv
  metrics_path: reports/metrics.json
  label_column: label
  dvclive_dir: dvclive/evaluation
